//post actions

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FUFILLED = 'FETCH_POSTS_FUFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
export const DELETE_POSTS_FUFILLED = 'DELETE_POSTS_FUFILLED';
export const NEW_POST = 'NEW_POST';
export const EDITED_POST = 'EDITED_POST';
export const FIND_SINGLE_POST = 'FIND_SINGLE_POST';
export const CHANGE_EDIT_STATUS = 'CHANGE_EDIT_STATUS';
export const CHANGE_REDIRECT_STATUS = 'CHANGE_REDIRECT_STATUS';
export const CURRENT_POST = 'CURRENT_POST';

//sign up actions
export const SIGN_UP_REDIRECT_YES = 'SIGN_UP_REDIRECT_YES';
export const SIGNUP_REDIRECT_NO = 'SIGNUP_REDIRECT_NO';
export const AUTHENTICATED_YES = 'AUTHENTICATED_YES';
export const AUTHENTICATED_NO = 'AUTHENTICATED_NO';
export const LOGGED_OUT = 'LOGGED_OUT';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const CLOSE_ALERT = 'CLOSE_ALERT';
